[world state]: fix compilation
After https://github.com/robotology/yarp/commit/31bdd9ab4f8cc9a2e0e9089afffdfc67b6159f69, it is now necessary to explicitly include Value.h, which is no longer included from Bottle.h.

This fixes the following compilation error:

/home/g/NOBACKUP/poeticon_upstream/src/worldStateVisualizer/src/WorldStateVisualizerThread.cpp:154:36: error: invalid use of incomplete type ‘class yarp::os::Value’
                 area = pos2d.get(0).asDouble();
                                    ^
In file included from /home/g/NOBACKUP/yarp/src/libYARP_OS/include/yarp/os/Contact.h:14:0,
                 from /home/g/NOBACKUP/yarp/src/libYARP_OS/include/yarp/os/ConnectionReader.h:14,
                 from /home/g/NOBACKUP/yarp/src/libYARP_OS/include/yarp/os/PortReader.h:14,
                 from /home/g/NOBACKUP/yarp/src/libYARP_OS/include/yarp/os/Portable.h:13,
                 from /home/g/NOBACKUP/yarp/src/libYARP_OS/include/yarp/os/Bottle.h:10,
                 from /home/g/NOBACKUP/poeticon_upstream/src/worldStateVisualizer/include/WorldStateVisualizerThread.h:19,
                 from /home/g/NOBACKUP/poeticon_upstream/src/worldStateVisualizer/src/WorldStateVisualizerThread.cpp:10:
/home/g/NOBACKUP/yarp/src/libYARP_OS/include/yarp/os/Searchable.h:18:15: error: forward declaration of ‘class yarp::os::Value’
         class Value;
               ^